# Generated by Django 3.1.7 on 2021-10-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('empId', models.CharField(max_length=500)),
                ('joinDate', models.DateField(blank=True, null=True)),
                ('bankName', models.CharField(max_length=500)),
                ('accountNo', models.CharField(max_length=500)),
                ('ifsc', models.CharField(max_length=500)),
                ('panNo', models.CharField(max_length=500)),
                ('department', models.CharField(max_length=500)),
                ('months_of_days', models.IntegerField()),
                ('designation', models.CharField(max_length=500)),
                ('arrearDays', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('Over_Time', models.CharField(max_length=500)),
                ('daysPaid', models.CharField(max_length=500)),
                ('daysLWP', models.CharField(max_length=500)),
                ('basic', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other', models.DecimalField(decimal_places=2, max_digits=10)),
                ('basicSalary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ecm_hra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ecm_other', models.DecimalField(decimal_places=2, max_digits=10)),
                ('incentive', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('esi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tds', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
